// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8t0d_h6lr-f5oPpETzXqCnuMsIrWhpzc',
    appId: '1:131870433085:web:9217003b070d61db606f54',
    messagingSenderId: '131870433085',
    projectId: 'fir-37c1b',
    authDomain: 'fir-37c1b.firebaseapp.com',
    storageBucket: 'fir-37c1b.firebasestorage.app',
    measurementId: 'G-10ECEBVFG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCikEZ1GrQVnj7n9JgYHriPh9Urp8ly4MA',
    appId: '1:131870433085:android:71f39d4945a51804606f54',
    messagingSenderId: '131870433085',
    projectId: 'fir-37c1b',
    storageBucket: 'fir-37c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDel_l6wzOpDTbkDwBzGqBGOE2NDpg0y5M',
    appId: '1:131870433085:ios:2a47886900c438c7606f54',
    messagingSenderId: '131870433085',
    projectId: 'fir-37c1b',
    storageBucket: 'fir-37c1b.firebasestorage.app',
    iosBundleId: 'com.example.wadayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDel_l6wzOpDTbkDwBzGqBGOE2NDpg0y5M',
    appId: '1:131870433085:ios:2a47886900c438c7606f54',
    messagingSenderId: '131870433085',
    projectId: 'fir-37c1b',
    storageBucket: 'fir-37c1b.firebasestorage.app',
    iosBundleId: 'com.example.wadayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8t0d_h6lr-f5oPpETzXqCnuMsIrWhpzc',
    appId: '1:131870433085:web:4226a110aa69d35c606f54',
    messagingSenderId: '131870433085',
    projectId: 'fir-37c1b',
    authDomain: 'fir-37c1b.firebaseapp.com',
    storageBucket: 'fir-37c1b.firebasestorage.app',
    measurementId: 'G-TQY3Y9GZ51',
  );
}
